displayName=Spotlight
author=Pvff13
support=
description=Blacks out the screen at Darkmeyer while highlighting anything important, like the altar, banks and valuable drops. Can also be used outside of Darkmeyer.
tags=blackout,darkmeyer,vyre,thieving,altar,bank,highlight
plugins=com.spotlight.SpotlightPlugin
version=1.0.0
build=standard
